version: '3.1'
services:
    jenkins:
        container_name: kilpio_jenkins
        build:
            context: ./
        volumes:
            - ${HOST_DOCKER}:/var/run/docker.sock
            - ${HOST_JENKINS_DATA}:/var/jenkins_home
        ports:
            - 8080:8080
            - 50000:50000
        environment:
            - JENKINS_JAVA_OPTIONS=-Djava.awt.headless=true -Djenkins.install.runSetupWizard=false
            - JENKINS_DEBUG_LEVEL="9"