version: '3.1'
services:
    jenkins_ssl:
       container_name: jenkins-switch-to-ssl
       image: jgit_jenkins
       volumes:
           - ${HOST_DOCKER}:/var/run/docker.sock
           - ${HOST_JENKINS_DATA}:/var/jenkins_home
       command: sh -c 'cp /tmp/openssl.cnf /var/jenkins_home/ && cd /var/jenkins_home/ && /usr/local/bin/make_pks.sh'
