version: '3.1'
services:
    jenkins_ssl:
       container_name: jenkins-switch-to-ssl
       image: jgit_jenkins
       volumes:
           - ${HOST_DOCKER}:/var/run/docker.sock
           - ${HOST_JENKINS_DATA}:/var/jenkins_home
       command: sh -c 'cd /var/jenkins_home/ && /var/jenkins_home/make_pks.sh'
