version: '3.1'
services:
    jenkins:
        container_name: kilpio_jenkins
        build:
            context: ./
        restart: unless-stopped
        volumes:
            - ${HOST_DOCKER}:/var/run/docker.sock
            - ${HOST_JENKINS_DATA}:/var/jenkins_home
        ports:
            - 8080:8080
            - 50000:50000
